version: "3.8"

services:
  node_app:
    container_name: node_app
    build: .
    image: adriel/movierental
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=movierental
      - DB_USERNAME=adriel
      - DB_PASSWORD=admin
      - DB_HOST=node_db
      - NODE_ENV=development
    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=movierental
      - POSTGRES_USER=adriel
      - POSTGRES_PASSWORD=admin
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
